### PR TITLE
Add examples to session + add long_readme

### PR DESCRIPTION
**Pull request by asmaamagdoub**
We added examples to the `session` file, and reordered the functions.
Also we included the `long_readme.md` file along with relevant content from the old version of spanner_workbench.

### CODE REVIEW

**Review by DeanLight — CHANGES_REQUESTED** [review]
For the papers is the docs, can you remove the pdfs from the repo and instead put in the long readme a section of relevant papers with the links to the papers online?

**Review by DeanLight — APPROVED** [review]
other than that, the examples are good. You can merge after fixing the above requests.

**Comment by asmaamagdoub** [comment]
didn't find online links to all of them, including:
* papers/spanner_log_Y_nachshon.pdf
* doc/language_spec.pdf

**Comment by DeanLight** [comment]
> didn't find online links to all of them, including:
> 
> * papers/spanner_log_Y_nachshon.pdf
> * doc/language_spec.pdf

language_spec is not a paper, its a formal definition, it can stay as a pdf.

For nachshon et al, here it is : https://dl.acm.org/doi/10.1145/2932194.2932200

**Pull request merged**
